/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sean_abraham' at '5/23/16 12:34 AM' with Gradle 2.13
 *
 * @author sean_abraham, @date 5/23/16 12:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
