import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sean_abraham' at '5/23/16 12:34 AM' with Gradle 2.13
 *
 * @author sean_abraham, @date 5/23/16 12:34 AM
 */
public class LibraryTest {

  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
